### PR TITLE
Split skylighting (GPL) into skylighting-core (BSD3) and skylighting (GPL)

### PR DESCRIPTION
**Pull request by jtdaugherty**

### CODE REVIEW

**Comment by jgm** [comment]
What's the conflict involving `bin/main.hs`?

**Comment by jtdaugherty** [comment]
I guess there was a small change to your `master` that wasn't merged into my repo. That's done now.

**Comment by jtdaugherty** [comment]
Thank you!

**Comment by jgm** [comment]
OK, the merge should make things easier going forward, but we're not done.
I bumped versions to 0.7. Next problem is that the tests fail to compile.
I fixed an import, but that isn't enough -- the problem is that the tests (currently in skylighting-core) require defaultSyntaxMap, which only gets defined in Skylighting.

Possible solutions:

- move all tests to skylighting -- this leaves skylighting-core without tests, but maybe not a huge problem if development is always done in this repository
- revise skylighting-core tests to use dynamic loading of syntaxes, and add some further tests to skylighting to test the things it adds

**Comment by jtdaugherty** [comment]
Since the XML files are included in `core`, it seems to me that leaving the tests behind in `core` is better since then the tests are closer to the code they're testing, and we can load the XML files dynamically. I can work on that today.

**Comment by jgm** [comment]
Sounds good.

**Comment by jtdaugherty** [comment]
I've filed #38. This compiles, but on my system, all of the XML files fail to load with an "illegal URI" error that I don't understand. Can you shed any light on that?

Also, these failures cause a great deal of output to stderr due to the HXT parsing being in `IO`. The application that I'm working on that motivated all of this work is a curses-style application that controls the terminal, so error output from the parser will corrupt the terminal. Is there any other way to parse XML documents with HXT that doesn't entail getting such output?

**Comment by jtdaugherty** [comment]
(On second thought, we can easily just load all syntaxes before we take over the terminal, so it isn't a show-stopping issue.)

**Comment by jgm** [comment]
The argument is for a file path, not the xml contents - that was the problem. I've pushed a fix and now I'm working on travis.

**Comment by jtdaugherty** [comment]
Oh!

**Comment by jtdaugherty** [comment]
That explains why the XML was *in the error message*, which I found strange. I modified the parsing function to omit that from the error, thinking it odd, but now I realize that was a mistake. I'll revert it.

**Pull request merged**
