### PR TITLE
Add powerhsell syntax highlighting

### PR DESCRIPTION
**Pull request by KyleOndy**
I did not write this file, I got it from [m0t0k1/kate-powershell](https://github.com/m0t0k1/kate-powershell). There is no license in the repo, but the file itself specifies LGPL, so I do not know where the legality of using this file lies.

### CODE REVIEW

**Comment by KyleOndy** [comment]
I'm looking into adding a test for this file. Just need to familiarize myself with the syntax.

**Comment by KyleOndy** [comment]
It also appears the there is an [official](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/powershell.xml) powershell xml in KDE's repo.

**Comment by jgm** [comment]
We should use the official one, then.

+++ Kyle Ondy [Sep 28 17 05:29 ]:

**Comment by KyleOndy** [comment]
Thanks for adding the powershell xml in e27223aa511f572bf1efbf7fb1a58d41d2c75f15!

**Pull request closed without merging**
