### PR TITLE
Added *.el to commonlisp’s extensions

### PR DESCRIPTION
**Pull request by NightMachinery**

### CODE REVIEW

**Comment by jgm** [comment]
Isn't .el emacs lisp, not commonlisp?

**Comment by NightMachinary** [comment]
Indeed, but us poor elispers are better off with commonlisp’s highlighting
than no highlighting at all. (Unless there is elisp highlighting? I didn’t
see one ...)

**Comment by jgm** [comment]
Yeah.  I suppose nobody would use the Kate editor to edit emacs lisp, so nobody bothered to add a KDE syntax description for it.

I think a better solution would be to add an elisp.xml syntax description, which is actually tailored to elisp.  It could also be submitted upstream.

**Comment by NightMachinary** [comment]
Yes, but I’m not familiar enough with either elisp or KDE syntax
descriptions to do that.
If someone is not going to do that, please merge this in for the meantime.
Perfect is the enemy of the good.

**Comment by jgm** [comment]
Well, for now you can use your own version of commonlisp.xml using the dynamic loading feature.

**Comment by NightMachinary** [comment]
What’s this dynamic loading? Note that I’m using pandoc, and not
skylighting directly ...

**Comment by jgm** [comment]
With pandoc, check out the [`--syntax-definition`](https://pandoc.org/MANUAL.html#option--syntax-definition) option.

**Comment by jgm** [comment]
fixed upstream and in skylighting

**Pull request closed without merging**
