### PR TITLE
Add `case` keyword

### PR DESCRIPTION
**Pull request by steinwaywhw**

### CODE REVIEW

**Comment by steinwaywhw** [comment]
The check is ok for ATS language. The failure in TravisCI is due to two other languages, Troff Mandoc and Roff.

**Comment by jgm** [comment]
Have you submitted something upstream to the KDE syntax
highlighting repository?

+++ Hanwen (Steinway) Wu [Apr 21 17 06:53 ]:

**Comment by steinwaywhw** [comment]
Oh, I didn't. Actually I didn't know there is such a repo. Where should I submit the PR?

**Comment by jgm** [comment]
The repository is

https://github.com/KDE/syntax-highlighting

However, I just realized that ats.xml is not in this
repository; it must have been something submitted to
skylighting but never upstream.

Submitting it (or your revised version) upstream would
be a good idea, but we can still fix it here via this
PR.

+++ Hanwen (Steinway) Wu [Apr 21 17 13:01 ]:

**Pull request merged**
