### PR TITLE
Ensure line span css only applied to lines

### LINKED ISSUE #79: [HTML] Highlighted inline code within strikeout is not applied correctly
Consider: ``~~foo `constexpr`{.cpp} bar~~``
With `pandoc foo.md --output foo.html --self-contained` this currently generates:
Screen Shot 2019-06-13 at 10 46 58 PM

The desired output would be something like:
Screen Shot 2019-06-13 at 10 47 19 PM

---

This seems to be caused by the `display: inline-block` from https://github.com/jgm/skylighting/blob/8c650b6e4aafc4c5eafb82d6e3449f3a67e066ee/skylighting-core/src/Skylighting/Format/HTML.hs#L170.
Changing this to `display: inline` produces the desired output.

### PR DESCRIPTION
**Pull request by dbaynard**
WIP. I haven't tested yet. Fixes #79 (eventually).

### CODE REVIEW

**Comment by jgm** [comment]
Great, let me know when this is ready to go.

**Comment by dbaynard** [comment]
I'm just checking pandoc with this new skylighting version, now. There's an issue with skylighting output in prince (though with chrome it works correctly) — I _think_ the problem there is prince.

**Comment by dbaynard** [comment]
Any advice on building pandoc with custom skylighting?

In the past, I've just vendored my variant of the package, then bootstrapped. It would be nice if it could bootstrap as part of the build (I'd happily implement this as a custom build!).

**Comment by jgm** [comment]
If you just want to do it locally, then bootstrap
skylighting (say in a skylighting subdirectory of
pandoc).  Then replace the lines in pandoc's
stack.yaml that refer to skylighting and
skylighting-core with

- skylighting/skylighting
- skylighting/skylighting-core

and build with stack.

**Comment by dbaynard** [comment]
The custom pandoc produces the desired output, and I've confirmed the resulting html is as expected, more generally and that epub output is ok and passes the validator.

The pandoc test suite fails for `lhs-test.html` and `lhs-test.html+lhs`, because the tests expect the output to contain the old skylighting css.

---

###### Chrome (screen)

skylighting-html

###### Chrome (print)

chrome-print

###### Prince (print)

This was also broken before — I think the issue is my prince configuration.

prince-print

**Comment by jgm** [comment]
Thanks.  I may consider changing that pandoc test to turn off highlighting; it causes problems!

**Comment by dbaynard** [comment]
I was hoping to have a better was to manage the CSS; it's hard to justify adding a dependency on clay given that it isn't really being maintained. It should make it easier in future to see what the sections do. If I can't come up with a good solution, I'll just add extra documentation (otherwise I'll improve and document).

**Pull request merged**
