### PR TITLE
Add Nim syntax

### PR DESCRIPTION
**Pull request by danipozo**
Adds Nim XML syntax file from https://github.com/juancarlospaco/NimKate

### CODE REVIEW

**Comment by jgm** [comment]
Is there no nim.xml in the KDE repository?
If not, has this been submitted upstream?

**Comment by danipozo** [comment]
I'm guessing it's [this repo](https://github.com/KDE/syntax-highlighting). In that case, no, there is no nim.xml there. Is it preferable that I submit this in that repo?

**Comment by jgm** [comment]
Correct.  We can merge it here before it's accepted there, but I like things to be at least submitted, because periodically we resync with the KDE definitions.

**Comment by jgm** [comment]
Also it would be good to include author and license attributes on the top-level element.

**Comment by danipozo** [comment]
I have added the author and license to the XML file, and submitted [this PR](https://github.com/KDE/syntax-highlighting/pull/25) which I hope is noticed at some point. That's the most I can do now about submitting this upstream.

**Comment by jgm** [comment]
great, thanks.

**Pull request merged**
