### PR TITLE
Added basic Swift support.

### PR DESCRIPTION
**Pull request by Elland**

### CODE REVIEW

**Comment by jgm** [comment]
Have you submitted this upstream to KDE?

**Comment by Elland** [comment]
@jgm not yet, the plan was to do it right away, but I went down a rabbit hole trying to build pandoc with my fork of this library today.

We could close this until I get everything sorted out and submit it upstream first.

**Comment by jgm** [comment]
No problem to leave this open while you do that.

**Comment by Elland** [comment]
@jgm MR completed upstream. 🚀

**Comment by jgm** [comment]
Great, can you link here to the upstream issue?

**Comment by Elland** [comment]
@jgm 
https://invent.kde.org/frameworks/syntax-highlighting/-/tree/7f740e4f2052c0d9be3df6c47bb95617257590ab
https://invent.kde.org/frameworks/syntax-highlighting/-/issues/11

**Comment by jgm** [comment]
Thanks!

**Comment by Elland** [comment]
@jgm would it be possible to push the new changes to hackage as well?

**Comment by jgm** [comment]
Eventually they will be.

**Pull request merged**
